apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: marketplace
  region: us-east-1
  version: "1.22"
nodeGroups:

    
  - name: test
    instanceType: t3.xlarge
    minSize: 1
    maxSize: 400
    desiredCapacity: 1
    volumeType: gp3
    volumeSize: 50
    kubeletExtraConfig:
        kubeReserved:
            cpu: "200m"
            memory: "200Mi"
            ephemeral-storage: "1Gi"
        kubeReservedCgroup: "/kube-reserved"
        systemReserved:
            cpu: "200m"
            memory: "300Mi"
            ephemeral-storage: "1Gi"
        evictionHard:
            memory.available:  "100Mi"
            nodefs.available: "10%"
        featureGates:
            RotateKubeletServerCertificate: true
    
