apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: marketplace
  region: us-east-1
  version: "1.22"
nodeGroups:

    
  - name: userapp
    instanceType: t3.xlarge
    minSize: 1
    maxSize: 4
    desiredCapacity: 1
    volumeType: gp3
    volumeSize: 50
    kubeletExtraConfig:
        kubeReserved:
            cpu: "200m"
            memory: "200Mi"
            ephemeral-storage: "1Gi"
        kubeReservedCgroup: "/kube-reserved"
        systemReserved:
            cpu: "200m"
            memory: "300Mi"
            ephemeral-storage: "1Gi"
        evictionHard:
            memory.available:  "100Mi"
            nodefs.available: "10%"
        featureGates:
            RotateKubeletServerCertificate: true
    ssh:
      allow: true
      publicKeyName: "cloudifytests"


    labels: {role: worker}
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
        imageBuilder: true
        autoScaler: true
        appMesh: true
        appMeshPreview: true
        ebs: true
        efs: true
        albIngress: true
        xRay: true
        cloudWatch: true
