apiVersion: v1
kind: Service
metadata:
  
  name: playwright
  
  
spec:
  
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 5010
    protocol: TCP
    targetPort: 5010
  selector:
    app: playwright
  sessionAffinity: None
  type: ClusterIP
